### ISSUE TITLE
Changes to initial cut of tests for base-docker-support/base-image

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#16]
**Task to do**
Change some tests for better coverage

**Reason**
Changes to help expand testing in the future and for better coverage

**Result**
- [x] Run testing code through pylint (using rc file at root of Organization-info repo
- [x] Place testing files into a test folder as possible (eg: base-image/test)

test_entrypoint.py:
- [x] test_handle_result(): change 'print' to 'file' and perform a file check

test_transformer.py:
- [x] transformer.check_continue() actually returns a tuple (template needed updating)
