### ISSUE TITLE
Add a base docker image override to configuration.py for template

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#18]
**Task to do**
Add another variable to configuration.py that the generate_docker.py script can use as the base image

**Reason**
Currently there's only a command line parameter override that allows the base image to be changed when generating Dockerfile. This will allow a more permanent change that won't rely on command line parameters being remembered

**Result**
The variable will allow the override of the base image for Dockerfile, and still allow the command line override to take precedence

**Steps to take**
- [x] Update the template-transformer-simple repo to and and use the new variable
- [x] Document this variable and how it interacts with the command line parameter
- [x] Propagate update to ~~ua-gantry-transformer~~ and other template repos
- [x] Create Pull Request

**Comment by Chris-Schnaufer** [comment]
Main PR: https://github.com/AgPipeline/template-transformer-simple/pull/11
