### ISSUE TITLE
Convert base image container in base-docker-support to use Python3.7

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#19]
**Task to do**
To support python 3.7 change the links in /usr/bin for Python3 to point to Python3.7. Also add a link for python to run python 3

**Reason**
Python 3.7 has additional features that are useful for timestamp conversions and other benefits

**Result**
Scripts will run Python3.7 by default (and not 3.6)

**Command to add to Dockerfile**
- [x] ln -sfn /usr/bin/python3.7 /usr/bin/python3
- [x] ln -sfn /usr/bin/python3.7m /usr/bin/python3m
- [x] ln -sfn /usr/bin/python3 /usr/bin/python
- [x] Create Pull Request

**Comment by Chris-Schnaufer** [comment]
Pull request: https://github.com/AgPipeline/base-docker-support/pull/10
