### ISSUE TITLE
Proposal to evolve transformer architecture

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#27]
**Task to do**
Write a proposal and plan to modify the transformer architecture

**Reason**

We want to balance reliability, reproducibility, and developer ergonomics of the pipeline transformers

**Result**

- A [lightweight architecture decision record](https://www.thoughtworks.com/radar/techniques/lightweight-architecture-decision-records) checked into [AgPipeline/computing-pipeline](https://github.com/AgPipeline/computing-pipeline/) to capture the requirements, reasoning, solution, and implementation plan
- ZenHub epic and GitHub issues for the implementation plan

**Steps to take**

- [ ] Summarize and justify requirements for transformers (david starts this) agpipeline/issues-and-projects#152
- [ ] Give reasons why current solution doesn't meet all of these = generalize to explanation of our decisions, analysis of trade-offs. 
- [ ] Write a draft proposal to evolve the current solution so it meets all the requirements
    - [ ] migrate this to wiki; summarize etc
    - [ ] dig up other stuff too. 
    - [ ] why dag workflows? (see gist) vs message queue
- [ ] Create an iterative plan with steps to implement the proposal
- [ ] Get approval from David for proposal and the plan to implement it
- [ ] Create epic with issues for the plan

**Comment by julianpistorius** [comment]
Related proof of concept: https://github.com/AgPipeline/issues-and-projects/issues/132

**Comment by dlebauer** [comment]
Is this done? What remains to be done on this other than documenting the notes and creating new issues?

**Comment by dlebauer** [comment]
closing, all subtasks complete and >3 years old. no longer relevant to open projects
