### ISSUE TITLE
Use ua-gantry-pipeline template-rgb-plot to develop new version of Canopy Cover

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#33]
**Task to do**
Redevelop Canopy Cover algorithm to use plot-level template

**Reason**
Reduces the specialized code that needs to be maintained

**Result**
- Focussed canopy cover algorithm
- Testing out new template-rgb-plot code
- Demonstrates common algorithm sourcing and a possible implementation strategy

**Steps to take**
- [ ] Create new repo to hold derived algorithms
- [ ] Submodule current plot-level canopy cover (https://github.com/Chris-Schnaufer/canopy-cover)
- [ ] Create Dockerfile to create new image
- [ ] Create any other scripts to assist Dockerfile
- [ ] Test new Docker image
- [ ] Make new image available

**Comment by Chris-Schnaufer** [comment]
Closing as (partially) duplicate; see https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/30 for remaining work
