### ISSUE TITLE
Modify DPP workflow to add metadata to Clowder instance

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#37]
**Task to do**
Enable loading metadata to Clowder

**Reason**
Leverage Clowder search capabilities

**Result**
Metadata is available in Clowder

**Steps to take**
- [ ] Determine what data to store in Clowder (work with David)
- [ ] Add ability to create Clowder datasets (in spaces and collections) to hold metadata to workflow environment
- [ ] Add metadata upload to workflow

**Comment by Chris-Schnaufer** [comment]
Closing as no longer relevant
