### ISSUE TITLE
Ensure all captured data at ua-mac field site are delivered to UA

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#38]
**Task to do**
All data captured at the Maricopa field site is shipped to UA. 

**Reason**
This not only is a necessary first step but also allows longer term testing of transfers before entering production mode, determination of space requirements, and other logistics.

**Result**
Data captures regularly are available for UA processing

**Steps to take**
- [x] Data is transferred to UA
- [x] Data is appropriately stored with no overwrites or deletions in a manner allowing easy discovery
- [ ] Data is available for processing

**Comment by Chris-Schnaufer** [comment]
Julian will check in with Max and determine the state of the transfer. After that, decide if this needs to be an epic and write more tickets, or update ticket & point estimate

**Comment by julianpistorius** [comment]
Data now arrives at UA thanks to this PR by @max-zilla: 

https://github.com/terraref/computing-pipeline/pull/592

![Screen Shot 2019-12-10 at 9 30 01 AM](https://user-images.githubusercontent.com/742633/70555760-95698480-1b77-11ea-8432-dfcc4a4fb097.png)

I think it's over to @tedgin now to index it in IRODS.

**Comment by julianpistorius** [comment]
Update: New crop data is now automatically deposited here on the fieldscanner-data.arizona.edu host:

```
/irods_vault/terraref-ds06/home/shared/terraref/ua-mac/raw_data/
```

On Thursday @tedgin will set up set up an `inotify` listener for events on the `/irods_vault/terraref-ds06/home/shared/terraref/ua-mac` folder and subfolders.

> When new files are uploaded, `inotify` needs to call the iRODS iCommand `ireg` on it to register the file into iRODS

**Comment by julianpistorius** [comment]
Update: Nirav would like us to tar the files up into (daily?) batches.

**Comment by julianpistorius** [comment]
@dlebauer I am making some assumptions that I'd like you to double-check:

1. The periodic batch files is per sensor. In other words, for each period, there will be a separate tar file for each sensor. Something like:

```
stereoTop_2020-01-29.tar
flirIrCamera_2020-01-29.tar
...
```

(As opposed to all the files for all the sensors going in the same tar file for the period.)

2. The period for the batches is calendar day, based on the date directory names inside each sensor directory (e.g. all files under `stereoTop/2020-01-29/**` will go into `stereoTop_2020-01-29.tar`)

3.  A tar file will contain paths which contain the sensor name as well as date directory. For example:

```
stereoTop/2019-12-10/2019-12-10__12-15-04-656/06d7901c-e0aa-40a1-87e1-1377755c9d68_right.bin
stereoTop/2019-12-10/2019-12-10__12-15-04-656/06d7901c-e0aa-40a1-87e1-1377755c9d68_left.bin
stereoTop/2019-12-10/2019-12-10__12-15-04-656/06d7901c-e0aa-40a1-87e1-1377755c9d68_metadata.json
```

That way someone can un-tar multiple sensor tar files for multiple periods in the same directory and get the equivalent of the contents of the `raw_data` directory.

4. If there are no files for a period for a sensor, then there will be no tar file for that sensor-period combination (as opposed to creating an empty tar file).

---

Something I still have to figure out: What to do if files show up for a day, after a tar file for that day has been created and uploaded to the data store (and possibly even been processed).

Options:

A. Create an 'addendum' tar file for the period, containing only the new files since the previous tar file (which could have been a previous addendum tar file)
B. Recreate the tar file for the period, including the old and new files, with the same name
C. Create a new tar file for the period, including the old and new files, with a new name to indicate a new 'version'
D. ???

**Comment by dlebauer** [comment]
I think by sensor by day is a good option. 

A few things to consider:
* there are often many scans per day and some night scans continue through two days, so a single day might not contain an entire scan. Another option would be to group by sensor and scan name rather than by date. Scan name can be found in the metadata if that helps.
* some sensors have very small datasets and could be combined into one and still be <<1GB while other sensors such as the hyperspectral could be on the order of 0.5-1 TB/d and depending on what is going on, it might be worthwhile to reduce this. For example, if someone wants to check out a particular 20GB hyperspectral file, do they have to download 1TB? 
 

> What to do if files show up for a day, after a tar file for that day has been created and uploaded to the data store (and possibly even been processed).

When would this happen? Can't we wait until all of the data has been collected and transferred? Otherwise, I would go with "B. Recreate the tar file for the period, including the old and new files, with the same name" as a stopgap, but try to figure out why this is occurring.

**Comment by Chris-Schnaufer** [comment]
Hello Julian, I agree with David and am voting for option B. Also, tar-ing the files by scan name and naming the by the start date - I think it's the way to go

**Comment by elyons** [comment]
I'm voting "c" so that if someone has download the previous version, they have a quick way to see that they need to delete the old version they have and get the new version.

**Comment by dlebauer** [comment]
I agree with Eric about using a simple way to identify the new version, so c is a sensible option. 

But my understanding is that this should be the exception, i.e., it is possible to know at the time of packaging that the dataset is complete, so any time such an exception occurs, there should be a notification so that we can check if there is a bug, faulty logic in the code, or something unexpected in the data capture and transfer that should be investigated.

It doesn’t seem that it would be necessary to keep the old version around (since the new version is just a superset of the old version).

**Comment by julianpistorius** [comment]
@elyons @dlebauer Heads-up. I have some initial numbers for `stereoTop`.

```
time tar c --directory=/irods_vault/terraref-ds06/home/shared/terraref/ua-mac/raw_data --file=/irods_vault/.tmp/tmp_stereoTop_2020-02-03.L5l/stereoTop-2020-02-03.tar stereoTop/2020-02-03

real    40m30.628s
user    0m9.736s
sys     4m45.302s
```

- It takes 40 minutes to create an uncompressed tar file for each day's `stereoTop` scan
- Almost all of it is just time spent in thrashing the disk like crazy, and not using much CPU
  - This backs up Rob/Max's recommendation to not to inflict this kind of IO load on the cache server's disks
- Each tar file will be around 140GB in size

If the large tar files turns into problem on the 'writing' side then we may want to look at [multi-volume tar files](https://unix.stackexchange.com/questions/504610/tar-splitting-into-standalone-volumes)

I imagine it will take a similar amount of time to un-tar on the worker/master nodes. Staging the data before processing is definitely going to be crucial.

If handling gigantic tar files will be a problem on the 'reading' side then we may want to look at not un-tarring the files at all, and just mount the tar file as a read-only filesystem using something like [archivemount](https://en.wikipedia.org/wiki/Archivemount).

An alternative to using tar files may be to use [netCDF and maybe THREDDS](https://github.com/Unidata/thredds)

The Cooperative Computing Lab folks (from Makeflow fame) also has the [Confuga Cluster File System](https://ccl.cse.nd.edu/software/confuga/):

> Confuga is an active storage cluster file system designed for executing DAG-structured scientific workflows. It is used as a collaborative distributed file system and as a platform for execution of scientific workflows with full data locality for all job dependencies.

Thoughts?

**Comment by julianpistorius** [comment]
When creating tar files it seems we're bottle-necked by read speed on the fieldscanner-data.arizona.edu (aka ds06.cyverse.org) server.

According to Andy Edmonds the specs for the disks on that machine are:

> Specs for DS06 /dev/sda:
> The /dev/sda disk is the raid container.  32 disk, ST8000NM0065, SAS 12gbps, AVAGO 3108 MegaRAID with 1G cache (read, write through).
The /dev/sdb and /dev/sdc disks are mirrored Toshiba MG03ACA100, 1TB SATA 6/gbps in the internal AHCI SATA controller. This mirror pair is the OS/boot disk. The raid container is mounted on /irods_vault. 

The raw read of the disk (/dev/sda1) with the files we're tarring up should be about 1500 MB/s. (If my calculations are correct.)

But when creating a tar file I see read speeds (using `iotop`) hovering between 60 and 70 MB/s, with occasional spikes around 90 MB/s. Not sure if it's the RAID adding overhead, or something else. :man-shrugging:

As a result it takes about 40 minutes to create a 140 GB tar file. Seems like it should take around 2 minutes with those specs.

**Comment by julianpistorius** [comment]
Note: CyVerse's IRODS installation (Data Store) does have the netCDF microservices enabled.

**Comment by julianpistorius** [comment]
See here for progress: https://github.com/AgPipeline/issues-and-projects/pull/123

**Comment by julianpistorius** [comment]
@dlebauer Closeable?
