### ISSUE TITLE
Create a template-lidar-plot repo and populate it

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#40]
**Task to do**
Create a Lidar plot-level template similar to [template-rgb-plot](https://github.com/AgPipeline/template-rgb-plot) template except dealing with Lidar data.

**Reason**
Enables plot-level Lidar algorithm developers to easily create working workflow components

**Result**
Have a repository that can be used as a template to create new workflow algorithms

**Steps to take**
- [x] Create algorithm_lidar.py template file (filled in)
- [x] Create generate.py executable script that's used to create Dockerfile and supporting files
- [x] Create testing.py executable script to be used when testing algorithm
- [x] Obtain plot-level lidar files, ZIP them together and place on google drive along side the RGB testing files
- [x] Create HOW_TO.md file with detailed instructions on how to use new template file
- [x] Let AgPipeline owner know when new repository is created so correct permissions can be applied to repo
- [x] Integrate into TravisCI: use testing.py script to validate default algorithm using ZIP of Lidar data (include pylint, etc as well)

Notes:
1. cloning the template-rgb-plot repo to use as a starting point is probably the fastest approach to finishing this
2. the generated Dockerfile should reference the Lidar specific base image (created through different ticket(s))

**Comment by Sithyphus** [comment]
Located here
https://github.com/Sithyphus/template-lidar-plot/tree/master
I need to move it to the main agpipline org repo, probably later today.

**Comment by Sithyphus** [comment]
Link above is no longer relevant, this repo has been moved to it's rightful home below
https://github.com/AgPipeline/template-lidar-plot/tree/master

**Comment by Sithyphus** [comment]
PR is located here
https://github.com/AgPipeline/template-lidar-plot/pull/1
