### ISSUE TITLE
Create base plot-level Lidar Docker image to be used with the template-lidar-plot derived repos

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#41]
**Task to do**
Create the base image used as with the template-lidar-plot repo. This is similar to the [rgb-plot-base-transformer](https://github.com/AgPipeline/drone-pipeline-transformer/tree/more_docker_images/rgb-plot-base-transformer) folder, except for Lidar [try the following link if the previous one doesn't work and browse to the a branch that has the folder name: https://github.com/AgPipeline/drone-pipeline-transformer]

**Reason**
As part of making writing Lidar plot-level algorithms easier, a base image is needed to provide the context the algorithm runs in

**Result**
Ability to create new Docker images that can be used as the basis for plot-level Lidar algorithms

**Steps to take**
- [x] Create a new folder, next to common-image in [ua-gantry-transformer](https://github.com/AgPipeline/ua-gantry-transformer) repository to hold files
- [x] Add configuration.py file and fill in with correct information
- [x] Add transformer.py file that provides the support needed for the lidar plot-level template
- [x] Add Dockerfile, requirements.txt, and packages.txt files used to build image for Lidar
- [x] Create README.md file and fill in to document the code
- [x] Create docker image that can be used
- [ ] Integrate TravisCI to test add_parameters(), check_continue(), and perform_process() functions only (don't add tests for other methods since they'll probably be moved; what's not moved will be added to TravidCI later), and to test Docker image

Note:
1. Clone the rgb-plot-base-transformer repo to get a quick start on what's needed
2. There should be quite a bit of overlap between the RGB and Lidar repos - the overlap should be put into a library; which is a separate issue

**Comment by Sithyphus** [comment]
https://github.com/AgPipeline/ua-gantry-environment/tree/lidar-docker-image
Here's the repo for the docker image and what not. The Travis part is not yet ready but will have a separate ticket associated with it.
