### ISSUE TITLE
IRODS ingestion of gantry data

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#6]
**Task to do**

Set up and document an automated process for ingesting gantry data into CyVerse Data Store (IRODS)

**Reason**

- [ ] Ease of access from VICE (for workbench/data exploration)
- [ ] Close to CyVerse & UA computational resources

**Result**

- Scripts and configuration necessary for setting this up
- Document (as text file in the code repository where the automation & logic end up)
- Monitoring & alerting (at least documenting what success/failure looks like)

**Steps to take**

- [x] Julian to talk to Tony, Edwin and Max to see what's involved in getting this done, and then add next steps below

**Comment by julianpistorius** [comment]
Currently this is at the stage of configuring the Globus endpoint with the right destination root directory on the dedicated IRODS storage node, and @max-zilla is working on this. (Correct me if I'm wrong.)

**Comment by julianpistorius** [comment]
Related to https://github.com/az-digitalag/organization/issues/56

**Comment by Chris-Schnaufer** [comment]
@julianpistorius What can be done with this ticket in "New Issues"? Can you fix it up?

**Comment by julianpistorius** [comment]
Update: @tedgin will be doing this part of https://github.com/AgPipeline/computing-pipeline/issues/38#issuecomment-564246963

**Comment by julianpistorius** [comment]
Continued in https://github.com/AgPipeline/issues-and-projects/issues/82
