### ISSUE TITLE
Clean up the SQLite database script

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#68]
**Task to do**
Clean up the SQLite generating script at https://github.com/Chris-Schnaufer/generate_sqlite

**Reason**
The script has problems and is tied to Chris Schnaufer's machine layout

**Result**
Code's cleaned up and made more flexible

**Changes to make**
Struck out lines were dependent upon Globus unless otherwise noted. The script was changed for local file access allowing Globus support to be removed. Look at the git tags for the last Globus supporting commit.
- [ ] ~~File layout strings should be made flexible - command line argument(s)?~~
- [ ] ~~Globus local endpoint ID is hard coded; sensor files are retrieved one-at-a-time and should be batched~~
- [x] Remove unused code
- [ ] ~~Add optional file cleanup flag (clean up by default, flag keeps downloaded files)~~
- [x] Convert all timestamps to 'YYYY-MM-DD HH:MI:SS' format (e.g.: '2018-04-02 12:13:46' ) when stored in database
- [x] Add indexes to tables to assist VIEWs created
- [ ] ~~Add index on weather&file view to place NULL file names last https://www.sqlite.org/lang_createindex.html~~ **(NULL file names are filtered out)**
- [x] Add timezone information to timestamps as supported by SQLite
- [x] Move repo to AgPipeline organization
- [x] Update README.md

Rename timestamp columns to local_XYZ

**Comment by Chris-Schnaufer** [comment]
Placing on hold while waiting for a solution to TERRA REF Workbench problem

**Comment by KristinaRiemer** [comment]
Moving this to backlog until Workbench is working.
