### ISSUE TITLE
Add ability for Transformers configuration to override (currently) mandated metadata file parameter

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#80]
**Task to do**
Allow Transformers to determine if metadata files are required

**Reason**
There are 'helper' Transformers that don't need metadata. For example, loading CSV files into BETYdb

**Result**
Transformers no longer **must** have metadata - specialized override/handling of this requirement is no longer needed

**Steps to take**
- [x] Add an option to Transformer configuration allowing the metadata requirement to be removed at runtime
- [x] Change the [coordination code](https://github.com/AgPipeline/base-docker-support/blob/master/base-image/entrypoint.py) to allow suppression of metadata parameter & requirement
- [ ] ~~Update transformers as needed to use new suppression feature~~
- [ ] ~~Release new transformer docker containers~~

**Comment by Chris-Schnaufer** [comment]
Need to write tickets for the rest of transformers needing changes as a result of top two check marks in original writeup
