### ISSUE TITLE
IRODS ingestion of gantry data (continue 01)

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#82]
Continuation of https://github.com/AgPipeline/issues-and-projects/issues/6

**Task to do**

Set up and document an automated process for ingesting gantry data into CyVerse Data Store (IRODS)

**Reason**

- [ ] Ease of access from VICE (for workbench/data exploration)
- [ ] Close to CyVerse & UA computational resources

**Result**

- Scripts and configuration necessary for setting this up
- Document (as text file in the code repository where the automation & logic end up)
- Monitoring & alerting (at least documenting what success/failure looks like)

**Steps to take**

- [x] Confirm these: https://github.com/AgPipeline/issues-and-projects/issues/38#issuecomment-580498348
- [x] Script to create tar files like specified above
- [x] Script to run `irsync` on tar files above
- [ ] Ensure tar file creation & `irsync` work reliably (or fail noisily)

**Comment by dlebauer** [comment]
I’ve addressed the open questions in #38 here: https://github.com/AgPipeline/issues-and-projects/issues/38#issuecomment-582019827 - so you can go ahead with option c: if new data appear after a tar is made, upload a new version that includes the version number in the name and delete the old one, with the caveat that the appearance of new data after packaging indicates a possible bug or error that should be investigated.

**Comment by julianpistorius** [comment]
Thanks David!

**Comment by julianpistorius** [comment]
Continued in https://github.com/AgPipeline/issues-and-projects/issues/93
